<?php
/**
 * Created by PhpStorm.
 * User: luhaoz
 * Date: 2017/12/22
 * Time: 10:43
 */


namespace luhaoz\cpl\curl;

class Curl extends \Curl\Curl
{
    public $multi = false;

    public function exec($exec = null)
    {
        if ($this->multi === false) {
            return parent::exec(); // TODO: Change the autogenerated stub
        } else {
            $this->response_headers = [];
            $this->response = $exec['response'];
            $this->curl_error_code = curl_errno($this->curl);
            $this->curl_error_message = curl_error($this->curl);
            $this->curl_error = !($this->curl_error_code === 0);
            $this->http_status_code = curl_getinfo($this->curl, CURLINFO_HTTP_CODE);
            $this->http_error = in_array(floor($this->http_status_code / 100), [4, 5]);
            $this->error = $this->curl_error || $this->http_error;
            $this->error_code = $this->error ? ($this->curl_error ? $this->curl_error_code : $this->http_status_code) : 0;
            $this->request_headers = preg_split('/\r\n/', curl_getinfo($this->curl, CURLINFO_HEADER_OUT), null, PREG_SPLIT_NO_EMPTY);
            $this->http_error_message = $this->error ? (isset($this->response_headers['0']) ? $this->response_headers['0'] : '') : '';
            $this->error_message = $this->curl_error ? $this->curl_error_message : $this->http_error_message;
            return $this->error_code;
        }
    }
}