<?php
/**
 * Created by PhpStorm.
 * User: luhaoz
 * Date: 2017/8/23
 * Time: 10:07
 */

namespace luhaoz\cpl\prototypeplugin\validate;

use luhaoz\cpl\dependence\Dependence;
use luhaoz\cpl\prototype\method\types\Method;
use luhaoz\cpl\prototype\plugin\base\BasePlugin;
use luhaoz\cpl\prototype\property\types\Value;
use luhaoz\cpl\validate\ValidateManager;

/**
 * Class PropertyValidatePlugin
 * @package luhaoz\cpl\prototypeplugin\validate
 */
class PropertyValidatePlugin extends BasePlugin
{
    const PLUGIN_NAME = 'propertyValidate';

    /**
     * @param null $owner
     * @return \luhaoz\cpl\prototype\property\types\Value
     */
    public function owner($owner = null)
    {
        return parent::owner($owner); // TODO: Change the autogenerated stub
    }

    public function initialise()
    {
        $this->owner()->prototype()->properties()->config('validator', Dependence::dependenceConfig(Value::class, [
            'default' => [],
        ]));
        $this->owner()->prototype()->properties()->config('__validator', Dependence::dependenceConfig(Value::class));
        $this->owner()->prototype()->methods()->config('validate', Dependence::dependenceConfig(Method::class, [
            '::method' => [[$this, '__propertyValidate']],
        ]));
        $this->owner()->prototype()->methods()->config('validator', Dependence::dependenceConfig(Method::class, [
            '::method' => [[$this, '__propertyValidator']],
        ]));
        $this->owner()->prototype()->methods()->config('validateData', Dependence::dependenceConfig(Method::class, [
            '::method' => [[$this, '__propertyValidateData']],
        ]));
    }

    public function __propertyValidateData()
    {
        return $this->toData();
    }

    public function __propertyValidate()
    {
        return $this->validator()->validate($this->validateData());
    }

    public function __propertyValidator()
    {
        if ($this->__validator === null) {
            $this->__validator = new ValidateManager();
            $this->__validator->configs($this->validator);
        }
        return $this->__validator;
    }
}