<?php
/**
 * Created by PhpStorm.
 * User: luhaoz
 * Date: 2017/8/29
 * Time: 17:38
 */

namespace luhaoz\cpl\prototype\property\types;

use luhaoz\cpl\util\Util;

/**
 * Class Primary
 * @package luhaoz\cpl\prototype\property\types
 */
class Primary extends Value
{
    public function get()
    {
        if ($this->isEmpty()) {
            $this->prototypeSet(Util::app()->generator->generate('primary_key'));
        }
        return parent::get(); // TODO: Change the autogenerated stub
    }
}