<?php
/**
 * Created by PhpStorm.
 * User: luhaoz
 * Date: 2017/6/30
 * Time: 15:19
 */

namespace luhaoz\cpl\prototype\behavior;

use luhaoz\cpl\dependence\DependencePool;
use luhaoz\cpl\prototype\base\BaseManager;
use luhaoz\cpl\prototype\behavior\types\Behavior;


/**
 * Class BehaviorManager
 * @package luhaoz\cpl\prototype\behavior
 */
class BehaviorManager extends BaseManager
{
    public function buildContainer()
    {
        $container = parent::buildContainer(); // TODO: Change the autogenerated stub
        $container->events()->on(DependencePool::EVENT_DEPENDENCE_CONFIG, function ($config) {
            $config['__hook.instantiate'] = function (Behavior $instance) use ($config) {
                $instance->owner($this->owner());
            };
            return $config;
        });
        return $container;
    }

    /**
     * @param $name
     * @return Behavior
     */
    public function behavior($name)
    {
        return $this->container()->dependence($name);
    }


}